### ISSUE TITLE
博客“关于”页面的链接有一个小问题

### ISSUE THREAD

**Issue by richardchien** [Abingcbc/blog#3]
<img width="282" alt="截屏2022-12-29 21 10 05" src="https://user-images.githubusercontent.com/5317095/209955605-8cdefba8-6cde-4c86-8bc5-14df42e22644.png">

句号被算在了链接里面，建议用 `<https://idvxlab.com/>` 也就是尖括号包裹链接（<https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses>）

**Comment by Abingcbc** [comment]
好滴，谢谢大佬
